# Utilisation de l’image Python officielle
FROM python:3.10

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers nécessaires
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exposition du port
EXPOSE 5000

# Commande d’exécution
CMD ["python", "app.py"]
