name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Affichage des versions de Docker et Python pour débogage
      - name: Show Docker version
        run: docker --version

      - name: Show Python version
        run: python --version

      # Étape 3: Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Étape 4: Affichage de la version de pip
      - name: Show pip version
        run: pip --version

      # Étape 5: Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true  # Permet de continuer même si l'étape échoue

      # Étape 6: Exécuter les tests
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings -v
        continue-on-error: true  # Permet de continuer même si l'étape échoue

      # Étape 7: Pruning des images Docker inutilisées
      - name: Prune unused Docker images
        run: docker system prune -f

      # Étape 8: Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t flask-app .
          docker images  # Affiche les images Docker après la construction

      # Étape 9: Connexion à Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Étape 10: Taguer et pousser l'image Docker vers Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag flask-app $DOCKER_USERNAME/flask-app:latest
          docker push $DOCKER_USERNAME/flask-app:latest
